name: Build Latest

on:
  push:
    branches: [ master ]

jobs:
  BuildLatest:
    runs-on: windows-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: Embed version
        run: |
          cd $env:GITHUB_WORKSPACE
          cmd /c version.bat

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1.0.2
        
      - name: Compile
        run: msbuild.exe $env:GITHUB_WORKSPACE\PolicyPlus\PolicyPlus.sln /p:platform="Any CPU" /p:configuration="Release"

      - name: Compute hash
        run: Get-FileHash "$env:GITHUB_WORKSPACE\PolicyPlus\bin\Release\Policy Plus.exe"

      - name: Upload to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: PolicyPlus\bin\Release\Policy Plus.exe
          asset_name: PolicyPlusMod.exe
          tag: ${{ github.ref }}
          overwrite: true
          body: "Tagged build"
 
